version: '2'

services:

  wordpress:
    image: beamonlabs/web3punkt0
    ports:
      - 9090:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    volumes_from:
      - wordpress_data
  wordpress_data:
    image: beamonlabs/web3punkt0

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes_from:
      - mysql_data

  mysql_data:
    image: mariadb
