version: '2'

services:
  web30:
    image: beamonlabs/web-3-punkt-0
    expose:
      - "80"
    environment:
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - web30_data:/var/lib/mysql

volumes:
  web30_data:
    external: true

networks:
  default:
    external:
      name: dmz

